//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFParisTraining.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA
    {
        public int ID { get; set; }
        public string UUID { get; set; }
        public Nullable<short> PDS_Role { get; set; }
        public Nullable<short> PLUS_Updated { get; set; }
        public Nullable<short> ESR_Updated { get; set; }
        public string RAComments { get; set; }
        public Nullable<System.DateTime> EGifL3 { get; set; }
        public Nullable<System.DateTime> PA1Rec { get; set; }
        public Nullable<System.DateTime> Declaration { get; set; }
        public Nullable<System.DateTime> Go_Live_Approved { get; set; }
        public bool GLA_Locked { get; set; }
        public Nullable<System.DateTime> Account_Created { get; set; }
        public Nullable<System.DateTime> Add_CITRIX { get; set; }
        public Nullable<System.DateTime> Password_Emailed { get; set; }
        public Nullable<System.DateTime> Access_to_Plus { get; set; }
        public Nullable<System.DateTime> UUID_Add_ESR { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
