//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFParisTraining.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServMem
    {
        public int Key { get; set; }
        public string Type { get; set; }
        public int ID { get; set; }
        public int ServID { get; set; }
        public bool Main { get; set; }
        public bool Pri { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
