//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFParisTraining.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sess()
        {
            this.Attendances = new HashSet<Attendance>();
        }
    
        public int ID { get; set; }
        public int CourseID { get; set; }
        public Nullable<int> TrainerID { get; set; }
        public Nullable<short> LocationID { get; set; }
        public Nullable<System.DateTime> Strt { get; set; }
        public Nullable<System.DateTime> Endt { get; set; }
        public short MaxP { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Course Course { get; set; }
        public virtual Location Location { get; set; }
        public virtual Staff Trainer { get; set; }
    }
}
