//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFParisTraining.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_List
    {
        public string Organisation__Team_ { get; set; }
        public Nullable<int> Employee_Number { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string UUID { get; set; }
        public string Paris_Staff_Code { get; set; }
        public string Staff_Group { get; set; }
        public string Job_Role { get; set; }
        public string NHS_Occupation_Code { get; set; }
        public string Position_Title { get; set; }
        public string Assignment_Number { get; set; }
        public string Assignment_Category { get; set; }
        public string PayPoint { get; set; }
        public Nullable<int> Cost_Centre { get; set; }
        public string Cost_Centre_Description { get; set; }
        public string Current_S12 { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public Nullable<bool> NHS_Pension { get; set; }
        public string Team_Cohort { get; set; }
        public string Cohort_Code { get; set; }
    }
}
