//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFParisTraining.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Teams = new HashSet<Team>();
            this.Minions = new HashSet<Staff>();
            this.TeamApprovs = new HashSet<TeamApprov>();
            this.TeamMems = new HashSet<TeamMem>();
            this.TNAs = new HashSet<TNA>();
        }
    
        public int ID { get; set; }
        public Nullable<short> TitleID { get; set; }
        public string Fname { get; set; }
        public string Sname { get; set; }
        public string PName { get; set; }
        public Nullable<Genders> Gender { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> Finance { get; set; }
        public Nullable<int> JobStatus { get; set; }
        public Nullable<int> LineMan { get; set; }
        public Nullable<int> CohortID { get; set; }
        public string UUID { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> LM { get; set; }
        public Nullable<bool> Trainer { get; set; }
        public Nullable<bool> LeftTrust { get; set; }
        public Nullable<bool> NoTraining { get; set; }
        public Nullable<bool> Bank { get; set; }
        public Nullable<bool> External { get; set; }
        public Nullable<int> ESRID { get; set; }
        public string MName { get; set; }
        public string Comments { get; set; }
        public string ADAccount { get; set; }
    
        public virtual Cohort Cohort { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams { get; set; }
        public virtual RA RA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Minions { get; set; }
        public virtual Staff Line_Manager { get; set; }
        public virtual Title Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamApprov> TeamApprovs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamMem> TeamMems { get; set; }
        public virtual TNA TNA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TNA> TNAs { get; set; }
        public virtual Cost_Centres Cost_Centres { get; set; }
        public virtual Subjective Subjective { get; set; }
    }
}
