//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFParisTraining.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public short ID { get; set; }
        public string StatusDesc { get; set; }
        public bool Requirement { get; set; }
        public bool Attendance { get; set; }
        public bool RA_PDS { get; set; }
        public bool TNA_OUT { get; set; }
        public bool RA_PLUS { get; set; }
        public bool RA_ESR { get; set; }
    }
}
