//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFParisTraining.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMem
    {
        public int ID { get; set; }
        public int StaffID { get; set; }
        public int TeamID { get; set; }
        public bool Main { get; set; }
        public string Assignment { get; set; }
        public bool Active { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
