//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFParisTraining.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.TeamMems = new HashSet<TeamMem>();
        }
    
        public int ID { get; set; }
        public string TeamName { get; set; }
        public string ESR { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> LeaderID { get; set; }
        public Nullable<int> CohortID { get; set; }
        public Nullable<bool> NoTrain { get; set; }
        public bool Dont_Migrate { get; set; }
    
        public virtual Cohort Cohort { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamMem> TeamMems { get; set; }
        public virtual Staff Leader { get; set; }
    }
}
