//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFParisTraining.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public short ID { get; set; }
        public string TitleValue { get; set; }
        public string AvailGenders { get; set; }
        public Nullable<Genders> DefaultGender { get; set; }
    }
}
