//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFParisTraining.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNA
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date_Received { get; set; }
        public Nullable<int> TrainerID { get; set; }
        public Nullable<System.DateTime> Contact_Date { get; set; }
        public string Contact_Outcome { get; set; }
        public Nullable<short> TNA_Outcome { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Staff Trainer { get; set; }
    }
}
